version: "3.8"

services:
  api:
    build:
      context: .
    container_name: audit-log-service
    ports:
      - "8080:9025"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: audit_logs
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: audit-log-db
    environment:
      POSTGRES_DB: audit_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
